version: '3.8'

services:
  # Redis for caching and message history
  redis:
    image: redis:7-alpine
    container_name: codet-redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - codet-network

  # Qdrant for vector search
  qdrant:
    image: qdrant/qdrant:latest
    container_name: codet-qdrant
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: always
    networks:
      - codet-network

  # Codet API
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: codet-api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
    env_file:
      - .env
    depends_on:
      - redis
      - qdrant
    restart: always
    networks:
      - codet-network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
    container_name: codet-frontend
    depends_on:
      - api
    restart: always
    networks:
      - codet-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: codet-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - frontend
    restart: always
    networks:
      - codet-network

volumes:
  redis_data:
    driver: local
  qdrant_storage:
    driver: local

networks:
  codet-network:
    driver: bridge
